### ISSUE TITLE
【Feature】无需手动调用 `console.log` 方法即可显示变量值

### ISSUE THREAD

**Issue by lorcannn** [ZiuChen/JSRunner#1]
我记得在用过一个 vscode 插件，可以时时运行并将变量运行时的值展示在右侧面板中。当时那个插件需要付费就没用了，如今忘记他的名字。

**Comment by lorcannn** [comment]
手动输入 `console.log(xxx)` 感觉还是太低效了。目前使用一个 vscode 插件： `javascript console utils`，来帮我快速打 log 😁

**Comment by ZiuChen** [comment]
感谢反馈！后面会研究一下加上

**Comment by ZiuChen** [comment]
已增加内置Snippet：`clg`用于快速输入`console.log`
https://github.com/ZiuChen/JSRunner/commit/ae72fb2ef2ea595f47eb27be2b0dff7a7e3146a7
